name: stylish
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  cached_network_image: ^3.3.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  easy_localization: ^3.0.7
  http: ^1.1.2
  dartz: ^0.10.1
  go_router: ^14.1.4
  get_it: ^7.6.7
  logger: ^2.0.2+1
  flutter_screenutil: ^5.9.0
  flutter_easyloading: ^3.0.5
  loading_animation_widget: ^1.2.0+4
  flutter_inset_box_shadow: ^1.0.8
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  multi_select_flutter: ^4.1.3
  device_preview: ^1.2.0
  file_picker: ^8.0.6
  carousel_slider: ^4.2.1
  gallery_image_viewer: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#FFF2F5"
  image: assets/images/splash_screen.png
  android_12:
    color: "#FFF2F5"
    image: assets/images/app_icon.png


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/
    - assets/translations/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
